runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/cloudgithub/index.html
    upload: dist/cloudgithub/index.html
  - url: /
    static_dir: dist/cloudgithub

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(./)?\..$
  - ^(./)?.\.json$
  - ^(./)?.\.md$
  - ^(./)?.\.yaml$
  - ^LICENSE
